// <auto-generated />
using System;
using CoreRazorExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreRazorExample.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250731121317_third")]
    partial class third : thirdBase
    {
    }
}
