// <auto-generated />
using System;
using CoreRazorExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreRazorExample.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250730193709_second")]
    partial class second : secondBase
    {
    }
}
