// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CoreRazorExample.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext)), Migration("20250731121317_third")]
    internal class thirdBase : thirdBaseBase
    {
    }
}